# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

url: https://eaststandart.github.io

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /fair/:name/
  notes:
    output: true
    permalink: /project/:name/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Includes & excludes
include: ["_pages"]
