# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

url: https://eaststandart.github.io

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Includes & excludes
include: ["_pages"]
