name: Generate Attendance Report to Discussions 

on:
  push:
    paths:
      - '_data/*-journal-attendance-*.json'

permissions:
  contents: write
  discussions: write

jobs:
  build_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pyyaml requests

      - name: Run Python Report Generator
        run: python bin/journalattendance.py
        env:
          MY_ADMIN_TOKEN: ${{ secrets.MY_ADMIN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
